// Generated by CoffeeScript 1.4.0
(function() {
  var debug, lookupSite, page, site, sites, _i, _len, _ref;

  debug = false;

  sites = {
    "www.facebook.com": [
      {
        pathname: ".*",
        xPath: "//div[@id='contentArea']//li[contains(@class,'uiUnifiedStory')]"
      }
    ],
    "www.boards.ie": [
      {
        pathname: "^/vbulletin/forumdisplay.php\?",
        xPath: "//tbody/tr/td[contains(@id,'td_threadtitle')]"
      }
    ]
  };

  for (site in sites) {
    _ref = sites[site];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      page = _ref[_i];
      if (page.pathname) {
        page.regexp = new RegExp(page.pathname);
      }
    }
  }

  lookupSite = function(host, pathname) {
    var _j, _len1, _ref1;
    if ((host != null) && (pathname != null)) {
      if (host in sites) {
        _ref1 = sites[host];
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          page = _ref1[_j];
          if (page.regexp && page.regexp.test(pathname)) {
            if (debug) {
              console.log("" + host + " " + pathname + " " + page.xPath);
            }
            return page.xPath;
          }
        }
      }
    }
    return null;
  };

  chrome.extension.onMessage.addListener(function(request, sender, callback) {
    var response;
    response = {
      xPath: lookupSite(request != null ? request.host : void 0, request != null ? request.pathname : void 0)
    };
    return callback(response);
  });

}).call(this);
